name: Deploy

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: reg.istry.cz/github-actions-demo

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: azure/setup-helm@v1
      - env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
        run: echo $KUBECONFIG_BASE64 | base64 --decode > .kubeconfig
      - run: helm repo add ondrejsika https://helm.oxs.cz
      - run: cat .kubeconfig
      - env:
          KUBECONFIG: .kubeconfig
        run: helm upgrade --install github-actions-demo ondrejsika/one-image --set image=reg.istry.cz/github-actions-demo --set host=github-actions-demo.k8s.sikademo.com
